### PR TITLE
Use `*.overpassql` file extension

### LINKED ISSUE #2806: Rename `*.txt` to `*.overpassql`
`*.overpassql` is now the recommended file extension for Overpass QL: [OSM Wiki: Overpass QL § File extension](https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#File_extension)
*(**Disclaimer:** I added that section after [some discussion](https://wiki.openstreetmap.org/wiki/Talk:Overpass_API/Overpass_QL#Recommended_file_extension?).)*
Also, it is the most widely used extension on GitHub, see https://github.com/users/FloEdelmann/projects/2/views/2

I propose to rename all Overpass QL files in this repo to `*.overpassql` for consistency.

Context: GitHub's syntax highlighting engine requires that 200 repositories use the same file extension before they consider supporting that syntax and file extension: https://github.com/github/linguist/issues/5890

### PR DESCRIPTION
**Pull request by FloEdelmann**
Closes #2806.

### CODE REVIEW

**Comment by vmiklos** [comment]
You forgot to run `make check` locally, which would point out that you need to run `cargo fmt` after your changes.

**Comment by vmiklos** [comment]
Tick the "allow edits from maintainers" checkbox at https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork if you want me to fix this up for you.

**Comment by vmiklos** [comment]
Indeed, I just got my push cmdline wrong :-)

**Comment by vmiklos** [comment]
Thanks!

**Comment by FloEdelmann** [comment]
Thanks for merging!

**Pull request merged**
